In [1]:
import numpy as np

In [2]:
a = np.array([[9, 6, 0, 0, 0],
              [0, 9, 0, 0, 0],
              [0, 0, 9, 0, 0],
              [0, 0, 0, 9, -5],
              [0, 0, 0, 0, 9]])
b = np.array([[52, 4, 6, 8, 9, 12],
              [2, 54, 6, 8, 9, 12],
              [2, 4, 56, 8, 9, 12],
              [2, 4, 6, 58, 9, 12],
              [2, 4, 6, 8, 59, 12],
              [2, 4, 6, 8, 9, 62]])

In [3]:
# compute eigensystem
[values, vectors] = np.linalg.eig(a)

print("The eigenvalues are: ", values.round(3))
print("The eigenvectors are: \n", vectors.round(3))

print("Verification: ")
for i in range(len(a)):
    ax = np.dot(a.copy(), vectors[:,i])
    lambdax = np.dot(values[i], vectors[:,i])
    print((ax - lambdax).round(1))

The eigenvalues are:  [9. 9. 9. 9. 9.]
The eigenvectors are: 
 [[ 1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.]]
Verification: 
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[ 0.  0.  0. -0.  0.]


In [4]:
[values, vectors] = np.linalg.eig(b)

print("The eigenvalues are: ", values.round(3))
print("The eigenvectors are: \n", vectors.round(3))
newVector = vectors[:,2] + vectors[:,3]

print("Verification: ")
for i in range(len(b)):
    bx = np.dot(b.copy(), vectors[:,i])
    lambdax = np.dot(values[i], vectors[:,i])
    print((bx - lambdax).round(1))

print("New Vector Verification: \n", (np.dot(b.copy(), newVector) - np.dot(values[2], newVector)).round())

The eigenvalues are:  [50. 91. 50. 50. 50. 50.]
The eigenvectors are: 
 [[-0.993  0.408 -0.465 -0.17  -0.008 -0.089]
 [ 0.051  0.408  0.873  0.457  0.007  0.088]
 [ 0.051  0.408 -0.073  0.79   0.204  0.098]
 [ 0.051  0.408 -0.073 -0.215 -0.894  0.098]
 [ 0.051  0.408 -0.073 -0.215  0.289  0.719]
 [ 0.051  0.408 -0.073 -0.215  0.276 -0.669]]
Verification: 
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[-0. -0.  0. -0.  0.  0.]
[-0. -0. -0. -0.  0.  0.]
New Vector Verification: 
 [0. 0. 0. 0. 0. 0.]
